title: Dr. Alok Tiwari (PhD, IIT-BHU)
logo: /assets/img/profile_image.png
description: Assistant Professor, Big Data Analytics, Goa Institute of Management, Goa
show_downloads: true
theme: jekyll-theme-minimal
