title: Alok Tiwari (PhD, IIT-BHU)
logo: /Profile_image.png
description: <p style="text-align: justify;">Unlocking healthcare insights with AI. I'm a researcher and Assistant Professor leveraging AI (Machine Learning, Deep Learning) to tackle healthcare challenges. My expertise in data science and medical image analysis helps unlock valuable insights for better diagnosis and treatment.</p>
show_downloads: true
theme: jekyll-theme-minimal
